# Generated by Django 2.2.1 on 2019-06-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190626_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='key',
        ),
    ]
