# Generated by Django 2.2.1 on 2019-06-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_reqinfo_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqinfo',
            name='my_pp',
            field=models.ImageField(blank=True, default='profile_picture/df.jpg', null=True, upload_to='profile_picture/'),
        ),
    ]
